export const constants = {
	SET_ADD_USER: 'SET_ADD_USER',
	SET_INIT_USER: 'SET_INIT_USER',
	SET_OPEN_ALERT: 'SET_OPEN_ALERT',
	SET_CLOSE_ALERT: 'SET_CLOSE_ALERT',
	SET_OPEN_CONFIRM: 'SET_OPEN_CONFIRM',
	SET_CLOSE_CONFIRM: 'SET_CLOSE_CONFIRM',
}
